### ISSUE TITLE
display HTML altair plots via GitHub pages

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/SARS2-prot-sub-counts#1]
@WillHannon-MCB, to follow up on our chat, the pipeline currently runs and generates HTML plots for each protein in `results/sub_counts_plots`. 

The docs are currently served from `./docs/`.

What we'd like is another `snakemake` rule that somehow copies the plots into `./docs/` and does whatever is needed in Jekyll to have a link on the main `index.md` page to the plot for each protein.

**Comment by WillHannon-MCB** [comment]
@jbloom, I have a solution to this, but I don't think I have permission to push my branch to the remote.

**Comment by jbloom** [comment]
You should be able to do a pull request. I put a branch protection rule preventing direct pushes to the `main` branch.

**Comment by WillHannon-MCB** [comment]
Yep, it was just a transient `.ssh_config` issue affecting all of my repos. I was able to fix it. 

I made a new pull request that includes all of the plots on the main page of the Github Pages site and is robust to adding or taking away plots.  It works with the `Snakemake` workflow.  #2

**Comment by jbloom** [comment]
Looks great, thanks @WillHannon-MCB for fixing this in #2.
